name: Update Major Version Tag

on:
  release:
    types:
      - released
      - edited

jobs:
  update-majorver:
    name: Update Major Version Tag
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@main
